### ISSUE TITLE
AS special case stacked area plot with gap

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#108]
Only one special case is chosen for each report, the reports that are not "meh" are proportionally plotted as empty gap.

The plot looks like this:

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/e73b6c03-0ea4-4f08-a7af-7879ab20d2e5)

Sorting first by total special case portion seems to fragment the plot.

Data: [as_stats3.csv](https://github.com/SichangHe/internet_route_verification/files/13684870/as_stats3.csv)

**Comment by SichangHe** [comment]
Sort last by special case portion:

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/bf72d22f-761b-4574-869f-6df45685f611)

**Comment by SichangHe** [comment]
Related: #75. Commit: https://github.com/SichangHe/internet_route_verification_meta/commit/7cc33f24cdff60905096be4e7c2eb521b3ec27a8

**Comment by cunha** [comment]
> Sort last by special case portion, and ignore ASes without special cases:
> 
> ![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/dede1cbb-3fe9-4ff8-b804-4fb67d0352bb)

I prefer this one over the previous one. Seems easier to read. The graph itself seems interesting enough to discuss and draw insights from.

**Comment by SichangHe** [comment]
<details><summary>Latest plots.</summary>

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/3fff4edb-a62e-48f0-a0fa-4e8980f23a1b)
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/d86a3211-cf9f-4342-8531-57cfe05cad5d)

[AS-special-case-percentages-stacked-area-squared.pdf](https://github.com/SichangHe/internet_route_verification/files/13701194/AS-special-case-percentages-stacked-area-squared.pdf)
[AS-special-case-percentages-stacked-area.pdf](https://github.com/SichangHe/internet_route_verification/files/13701196/AS-special-case-percentages-stacked-area.pdf)

</details>

**Comment by SichangHe** [comment]
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/75723eaa-06b7-4859-9a90-480963d70c57)

All RIBs.
