### ISSUE TITLE
Customer cone size in AS stats correlations

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#124]
https://publicdata.caida.org/datasets/as-relationships/serial-1/

**Comment by SichangHe** [comment]
Postponing because it is unlikely to be different than the correlation with #customer.

**Comment by SichangHe** [comment]
Well, I shall fix this soon.

**Comment by SichangHe** [comment]
Looking at the dataset, it seems to be simpler to just recursively follow and flatten the customer sets we already have. The results would be the same as parsing another file from CAIDA, right, @cunha?

**Comment by cunha** [comment]
One of the definitions in the CAIDA paper is to just follow customer links
recursively. Another is to also follow peer links and build a larger
customer cone. I think following just customers would be preferable in our
case.
