### ISSUE TITLE
Extra points/lines in CDF of number of rules for each AutNum

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#137]
Following #60

> We should add Tier-1, tier-2, and large content providers as points on top of the current blue line. We should also add an additional line for the CDF of “simple” (BGPq3-compatible) rules, and another line for the CDF of rules with indirect filters.

**Comment by SichangHe** [comment]
Tier-1s and IXP ASes from CAIDA AS Relationship DB:

```
# input clique: 174 209 286 701 1239 1299 2828 2914 3257 3320 3356 3491 5511 6453 6461 6762 6830 7018 12956
# IXP ASes: 1200 4635 5507 6695 7606 8714 9355 9439 9560 9722 9989 11670 15645 17819 18398 21371 24029 24115 24990 35054 40633 42476 43100 47886 48850 50384 55818 57463
```

@cunha, are these the ones we want on the plot and what else?

**Comment by SichangHe** [comment]
![Uploading image.png…]()

**Comment by SichangHe** [comment]
Also, I excluded ASes without aut-num objects. Maybe I should count them as 0s? But, that would mean the CDF should change or I should manually pile them up at the left.

**Comment by SichangHe** [comment]
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/dbaab232-e5d9-432f-bf12-d582f80b395c)

With the lines for BGPq3-compatible and incompatible aut-num objects.

**Comment by SichangHe** [comment]
The compatible aut-nums only count the ones that have rules, the ones that don't have rules are counted are incompatible… That does not make much sense.

So, below, I removed aut-nums without any rules from the compatible/incompatible CDF lines:

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/3ff372d9-6b0a-487d-bd37-ca7b584409dc)

**Comment by SichangHe** [comment]
Large content providers: Google, Amazon, Cloudflair, IBM, Facebook, ASNs @cunha?

**Comment by cunha** [comment]
```python
cloud_provider_asns = [
    8075,  # Microsoft
    15169,  # Google
    16509,  # AWS
    32934,  # Facebook
    36351,  # Softlayer/IBM
]
```

**Comment by SichangHe** [comment]
```python
Tier-1 ASes without aut-num: {2828, 6453, 701, 6461, 7018}.
Tier-1 ASes with 0 rule: {209, 3491, 286, 1239}.
Large cloud providers without aut-num: set().
Large cloud providers with 0 rule: {8075, 13335}.
```

**Comment by SichangHe** [comment]
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/b892bc11-22dc-404a-b7f3-9d10f6114e0d)

I have normalized the two lower CDFs and added the giants.

**Comment by SichangHe** [comment]
Changing the plot to be #BGP-compatible rules per AS instead of #ASes with all rules BGP-compatible.

**Comment by SichangHe** [comment]
[bgpq3_compatible_rules.csv.gz](https://github.com/SichangHe/internet_route_verification/files/15190015/bgpq3_compatible_rules.csv.gz)

**Comment by SichangHe** [comment]
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/8540753e-a607-46c2-9c06-857340861015)

This looks bad, @cunha. Very few ASes use BGP-incompatible rules and the difference when plotting #rules for every AS is tiny.
I suggest we go back and plot the #ASes instead.

**Comment by cunha** [comment]
This looks OK. One suggestion is to make the "All" line dashed or dotted, so people can see that the other one is below. As for the result itself, this is expected, as very few ASes make advanced use of the RPSL. (Which can be seen as motivation for our work: advanced features cannot be used if the tools do not support them. We built one that improves the current situation.)

**Comment by SichangHe** [comment]
```python
Total: 792685 simple rules (97.4%) + 21463 complex rules (2.6%) = 814148 rules.
Tier-1 ASes without aut-num: {2828, 6453, 701, 6461, 7018}.
Tier-1 ASes with 0 rule: {209, 3491, 286, 1239}.
Large cloud providers without aut-num: set().
Large cloud providers with 0 rule: {8075, 13335}.
27818 (35.3%) aut-num objects have 0 BGPq4-compatible rules.
```

**Comment by SichangHe** [comment]
```python
27699 aut-nums (35.2%) contain no rules.
8557 aut-nums (10.9%) define at least 10 rules.
101 aut-nums (0.13%) define over 1000 rules.
```
