### ISSUE TITLE
Follow up on AS196844's route reports

### ISSUE THREAD

**Issue by cunha** [SichangHe/internet_route_verification#35]
Maybe we need updating the RPSL databases? Some of the reports don't match the RPSL:

```
TABLE_DUMP2|1687212000|B|94.156.252.18|34224|5.44.47.0/24|34224 196844 12831 197155 200088|IGP|94.156.252.18|0|0|34224:333 34224:334 34224:2010|NAG||:
    5.44.47.0/24 -> [Seq(34224), Seq(196844), Seq(12831), Seq(197155), Seq(200088)]
    MehExport { from: 200088, to: 197155, items: [Special(Uphill)] }
    MehImport { from: 200088, to: 197155, items: [Special(Uphill)] }
...
```

But the export from AS200088 looks OK:

```bash
[slardar:~]% whois AS200088
...
aut-num:        AS200088
as-name:        ARTNET2
org:            ORG-ASzo16-RIPE
import:         from AS197155 accept ANY
...
export:         to AS197155 announce AS200088
...
```

(I think this is the second report with apparent data mismatch.)

**Comment by cunha** [comment]
The AS-set regex seems to be an anti-feature, as people seem to be using it to perform *exact* matches, see

```
    SkipImport { from: 60243, to: 8308, items: [Skip(AsRegexUnimplemented("AS8308:AS-Customers:PeerAS$"))] }
    SkipExport { from: 8308, to: 196844, items: [Skip(AsRegexUnimplemented("AS-NASK:AS-Customers$"))] }
    SkipImport { from: 8308, to: 196844, items: [Skip(AsRegexUnimplemented("AS196844:AS-NASK-COM$"))] }
```

For these AS-set regexes that just have the string termination token (`$`) at the end, would it work to just do an exact match?

**Comment by cunha** [comment]
It is unclear why we get all the `AsRoutesUnrecorded` in the case below:

```
SkipExport { from: 12552, to: 49788, items: [Skip(AsRoutesUnrecorded(56901)), Skip(AsRoutesUnrecorded(58360)), ... many times
```

One problem is that `AS-IPO` is broken (doesn't have any `members`), but then we could just have a special `Special(AsSetEmpty)` or something.

```bash
[slardar:~]% whois AS12552 | grep 49788
import:         from AS49788 accept ANY
export:         to AS49788 announce AS-IPO
```

**Comment by cunha** [comment]
Overall not much else eyeballing this file. ALL reports for AS196844 are bad because it only has the AMS-IX policies, which doesn't match *anything* on AS-paths. I don't have a good idea for handling IXPs; possibly also something to bring up with Ethan when we talk to him.

* One thing I considered is that we could check whether the AS-pair (importer-exporter) are both members of the same IXP, and then tag the relationship as `Special(ColocatedAtIXP(ExportPolicy, ImportPolicy, IxpNumber))`. Let's discuss it.

**Comment by SichangHe** [comment]
> Maybe we need updating the RPSL databases? Some of the reports don't match the RPSL:
> 
> ```
> TABLE_DUMP2|1687212000|B|94.156.252.18|34224|5.44.47.0/24|34224 196844 12831 197155 200088|IGP|94.156.252.18|0|0|34224:333 34224:334 34224:2010|NAG||:
>     5.44.47.0/24 -> [Seq(34224), Seq(196844), Seq(12831), Seq(197155), Seq(200088)]
> ```
> 
> But the export from AS200088 looks OK:
> 
> ```shell
> export:         to AS197155 announce AS200088
> ```


The reason why the export AS200088 is marked "meh" is that `5.44.47.0/24` is not recorded in the `as_routes` of AS200088:

```rust
// A more verbose report.
    MehExport { from: 200088, to: 197155, items: [NoMatch(FilterAsNum(200088, NoOp)), NoMatch(RemoteAsNum(12831)), NoMatch(RemoteAsNum(15694)), Special(Uphill)] }
    MehImport { from: 200088, to: 197155, items: [NoMatch(RemoteAsNum(12831)), NoMatch(RemoteAsNum(6939)), NoMatch(RemoteAsNum(9002)), NoMatch(RemoteAsNum(6830)), NoMatch
(RemoteAsNum(24724)), Special(Uphill)] }
// …
>> query.as_routes.get(&200088)
Some([38.180.24.0/24, 38.180.34.0/24, 83.168.112.0/24, 83.168.113.0/24, 88.216.19.0/24])
```

**Comment by SichangHe** [comment]
> It is unclear why we get all the `AsRoutesUnrecorded` in the case below:
> 
> ```
> SkipExport { from: 12552, to: 49788, items: [Skip(AsRoutesUnrecorded(56901)), Skip(AsRoutesUnrecorded(58360)), ... many times
> ```

These are caused by not having `routes` associated with the ASes in the RPSL:

```rust
>> query.as_routes.get(&56901)
None
```

**Comment by SichangHe** [comment]
- [ ] Look at AS regex rules and handle simple cases.

**Comment by SichangHe** [comment]
> One problem is that `AS-IPO` is broken (doesn't have any `members`), but then we could just have a special `Special(AsSetEmpty)` or something.

It is not empty, it has a `set_member`:

```rust
>> query.as_sets.get("AS-IPO")
Some(AsSet { body: "descr: This AS-set exists for backward compatibility.\ndescr: It is not the AS-set you are looking for.\ndescr: Peers of AS12552, please use AS-GCNET.\ndescr: Staff at AS12552, please use AS12552:AS-GCNET.\nmembers: AS-GCNET\ntech-c: DUMY-RIPE\nadmin-c: DUMY-RIPE\nnotify: registry@ip-only.net\nmnt-by: IP-ONLY-MNT\ncreated: 2007-04-23T11:51:44Z\nlast-modified: 2022-05-31T10:38:04Z\nsource: RIPE\nremarks: ****************************\nremarks: * THIS OBJECT IS MODIFIED\nremarks: * Please note that all data that is generally regarded as personal\nremarks: * data has been removed from this object.\nremarks: * To view the original object, please query the RIPE Database at:\nremarks: * http://www.ripe.net/whois\nremarks: ****************************\n", members: [], set_members: ["AS-GCNET"] })
```

**Comment by SichangHe** [comment]
- [ ] Prune skips.
