### ISSUE TITLE
Comments on reports for AS8283

### ISSUE THREAD

**Issue by cunha** [SichangHe/internet_route_verification#36]
I wonder if we can make the case below more specific by checking that all import/export rules for AS57866 only refer to providers. In this case, we could relabel as 

- [x] ~~`Special(FromClientButOnlyProviderPolicies)` or something like it~~ `Special(C2PWOnlyP2CImport)` https://github.com/SichangHe/internet_route_verification/commit/c74380a39f0c34501cbad503280b941e75c8f8e5.

```
    MehImport { from: 8283, to: 57866, items: [Special(Uphill)] }
```

**Comment by cunha** [comment]
```
MehImport { from: 57866, to: 2914, items: [Special(Uphill)] }
```

Yeah, OK. Maybe we can just add a bit of info and label it `Special(UphillTier1)`.

**Comment by cunha** [comment]
```
BadExport { from: 11164, to: 2152, items: [] }
```

Seems like a check for "too few rules" could apply here. This network only has one export rule and no imports:
```bash
[slardar:~]% whois -h whois.radb.net AS11164  | grep -Ee '(import|export)'
export:     to AS6939   announce AS11164:AS-ALL
```

**Comment by SichangHe** [comment]
> Seems like a check for "too few rules" could apply here. This network only has one export rule and no imports

Yeah. But, the tricky part is how we set the threshold. Do we apply this rule if the other "port" is empty?
