### ISSUE TITLE
Statistics / visualization TODOs

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#38]
Raw stats data:

- [x] #57
- [x] #90
- [x] #108
- [x] #70
- [x] #71
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #97
- [x] #98

Graphs:

- [ ] AS #neighbors vs #good pairs
- [ ] AS %good pairs vs #RPSL rules
- [ ] %RPSL rules used (validity TBD)

**Comment by cunha** [comment]
<img width="798" alt="image" src="https://github.com/SichangHe/internet_route_verification/assets/325495/03f03f98-b808-4ea6-a890-0c2c6d1bb359">

**Comment by cunha** [comment]
<img width="850" alt="image" src="https://github.com/SichangHe/internet_route_verification/assets/325495/ae7b41fa-f194-435a-bed5-9f50c5d7ead5">

**Comment by cunha** [comment]
<img width="807" alt="image" src="https://github.com/SichangHe/internet_route_verification/assets/325495/a8846635-16b5-4985-a8d1-66b179eabff4">

**Comment by cunha** [comment]
CDF of routes vs % of good/meh/skip/bad AS-pairs: Discuss whether routes have mostly good pairs, or mostly similar pairs, or a mix of pair types.

**Comment by SichangHe** [comment]
---

route|n_good_pair|n_skip_pair|n_meh_pair|n_bad_pair
-----|-----------|-----------|----------|----------

$\sim 10^8$ words.

Or, with independent variable "% exchanged routes for each AS pair:"

as_pair|n_good_route|n_skip_route|n_meh_route|n_bad_route
-------|------------|------------|-----------|-----------

---

route|%meh_case_as1|%meh_case_as2
-----|-------------|-------------

Or, with independent variable "% routes for each AS:"

aut_num|n_good_route|n_skip_route|n_meh_route|n_bad_route
-------|------------|------------|-----------|-----------

**Comment by SichangHe** [comment]
Blocking on #65.

**Comment by SichangHe** [comment]
From #90 and #88 we see that the portion of skips is tiny and the portion of unrecorded is large, therefore I propose that we plot distribution of different unrec instead of skip.

**Comment by cunha** [comment]
+1
