### ISSUE TITLE
Comply with RFC 2622 as much as possible

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#41]
We are not considering some of the tricky rules in these RFCs.

- [x] AS set names.
- [x] Route set names.

Related: https://github.com/SichangHe/internet_route_verification/discussions/39#discussioncomment-6713864

**Comment by SichangHe** [comment]
- [ ] Find in the RFCs where the heck is `ASN:AS-X` allowed.

**Comment by SichangHe** [comment]
- [ ] Comply with the rules on sets.

**Comment by SichangHe** [comment]
- [ ] Check `mbrs-by-ref` and record AS sets that ASes refer to.

>  The mbrs-by-ref attribute is a list of maintainer names or the
>  keyword ANY.  If this attribute is used, the AS set also includes
>  ASes whose aut-num objects are registered by one of these maintainers
>  and whose member-of attribute refers to the name of this AS set.  If
>  the value of a mbrs-by-ref attribute is ANY, any AS object referring
>  to the AS set is a member of the set.  If the mbrs-by-ref attribute
>  is missing, only the ASes listed in the members attribute are members
>  of the set.

<https://www.rfc-editor.org/rfc/rfc2622#page-14>

**Comment by SichangHe** [comment]
- [ ] Check `mbrs-by-ref` for route sets.

**Comment by SichangHe** [comment]
Annotating in https://github.com/SichangHe/internet_route_verification_compliance/blob/main/rfcs/rfc2622.txt.

**Comment by SichangHe** [comment]
>  Once an rp-attribute is defined in the dictionary, it can be used to
>  describe policy filters and actions.  **Policy analysis tools are
>  required to fetch the dictionary object and recognize newly defined
>  rp-attributes, types, and protocols.**  The analysis tools may
>  approximate policy analyses on rp-attributes that they do not
>  understand:  a filter method may always match, and an action method
>  may always perform no-operation.  Analysis tools may even download
>  code to perform appropriate operations using mechanisms outside the
>  scope of RPSL.

- [ ] Do we need to check dictionaries?

**Comment by SichangHe** [comment]
>  Once an rp-attribute is defined in the dictionary, it can be used to
>  describe policy filters and actions.  **Policy analysis tools are
>  required to fetch the dictionary object and recognize newly defined
>  rp-attributes, types, and protocols.**  The analysis tools may
>  approximate policy analyses on rp-attributes that they do not
>  understand:  a filter method may always match, and an action method
>  may always perform no-operation.  Analysis tools may even download
>  code to perform appropriate operations using mechanisms outside the
>  scope of RPSL.

- [ ] Do we need to check dictionaries?

**Comment by cunha** [comment]
Advance use of PeerAS we can skip for now and revisit later:

```
$ whois -h whois.radb.net AS2764
...
	           from AS2764:AS-CUSTOMERS
	           accept PeerAS AND <^PeerAS+$>;
	           from AS2764:AS-TRANSIT
	           accept AS2764:AS-CUSTOMERS:PeerAS AND <^PeerAS+ AS2764:AS-CUSTOMERS:PeerAS~+$>;
	           from AS2764:AS-CUSTOMERS-APF
	           accept <^PeerAS+$>;
	           from AS2764:AS-TRANSIT-APF
	           accept <^PeerAS+ AS2764:AS-CUSTOMERS-APF:PeerAS~+$>;
```

**Comment by SichangHe** [comment]
- [ ] Doublecheck the `EXCEPT`/`REFINE` madness.

**Comment by cunha** [comment]
> * [ ]  Allow range operator after any route set in filter.
> 
> > A route set name can also be followed by one of the operators '^-',
> > '^+', example, { 5.0.0.0/8, 6.0.0.0/8 }^+ equals { 5.0.0.0/8^+,
> > 6.0.0.0/8^+ }, and AS1^- equals all the exclusive more specifics of
> > routes originated by AS1.

I thought we had decided not to implement this for now because it has only two uses in the databases?

**Comment by SichangHe** [comment]
Not for `<address-prefix-set>`s, for other "route set name: `<aut-num>`, `<as-set>`, `<route-set>`.

The RFC is being confusing here, talking about "route set name" while using `<address-prefix-set>`s as examples.

**Comment by SichangHe** [comment]
> * [ ]  Allow range operator after any route set in filter.
> 
> > A route set name can also be followed by one of the operators '^-',
> > '^+', example, { 5.0.0.0/8, 6.0.0.0/8 }^+ equals { 5.0.0.0/8^+,
> > 6.0.0.0/8^+ }, and AS1^- equals all the exclusive more specifics of
> > routes originated by AS1.

I just doublechecked this rule. We do comply with them.

The large number of warnings I see are "route set names" followed by the other operators—`^n` and `^m-n`. Base on this rule in the RFC, those are not allowed, but apparently, they are used everywhere.
