### ISSUE TITLE
AS path regex issues

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#42]
- [x] AS196844 RegexMismatch seems wrong.
- [x] AS139609 RegexMismatch seems wrong.
- [x] Do not dump unrecognized filters into `AsPathRE`.

**Comment by SichangHe** [comment]
@cunha, I changed `as_regex` so that the AS path is not reversed when converted to plain string. That is, it is ordered in the way it shows in bgp dumps.

To see which implementation is more likely correct, I ran them against AS196844's routes and counted the numbers of `RegexMismatch`. Unfortunately, it grew from 103 to 105.

I will compare other ASes next.

**Comment by SichangHe** [comment]
This change in reversion did not have an effect on AS47065. AS139609 does not have any more `RegexMismatch` anyways after I fixed another issue.

**Comment by SichangHe** [comment]
AS6939 sees a reduction from 3474 `RegexMismatch` to 1571 after removing the `.rev`, so it seems right to not reverse it.

Also, the reports' size reduced from 20GiB to 13GiB.

**Comment by SichangHe** [comment]
I tried again with AS6939 and got 3914 → 3876 `RegexMismatch`s, and the files are both 37GiB. Not sure what I did wrong there.

**Comment by cunha** [comment]
Can you paste some of the mismatches here (on tag me on a discussion thread) so I can go over them?

**Comment by SichangHe** [comment]
Sorry, the VM I was using had tons of bugs so I asked the admin to remove it and create a new one, which isn't up yet.

The biggest problem was the 37GiB file made the VM run out of space, so I couldn't keep it.

**Comment by SichangHe** [comment]
https://github.com/SichangHe/internet_route_verification/discussions/45?converting=1
