### ISSUE TITLE
Separate Skips due to RPSL error vs code handling

### ISSUE THREAD

**Issue by cunha** [SichangHe/internet_route_verification#59]
Some of the `SkipReason`s in the code seem to be due to errors in the RPSL (e.g., `RouteSetUnrecorded`) and some seem due to we not handling some corner cases (e.g., `CommunityCheckUnimplemented`). We should separate these so we can quantify them separately: RPSL errors are fine as it's a problem for the operator, corner cases we don't handle are a limitation we accepted. The limitations are fine, but we need to show that they don't apply frequently.

**Comment by SichangHe** [comment]
Solved by #66.
