### ISSUE TITLE
Check correspondence between `route` objects and route sets

### ISSUE THREAD

**Issue by cunha** [SichangHe/internet_route_verification#62]
Steven's Edit: For each AS `as-x` that only export a single Route Set `rs-y` or `Any`, check whether `rs-y` and `as-x` point to the same set of address prefixes.

---

An AS may define `route` and `route6` objects for its prefixes, and also maintain `route-set` objects. For these ASes, we should compute whether the `route` and `route-set` objects lead to the same set of IP prefixes, or if there are any differences.

**Comment by SichangHe** [comment]
This does not make sense to me because `route`s specify an `origin` that points to `aut-num`s, not `route-set`s. I do not expect defined `route-set`s to match an AS's `route`s. Also, there is no direct way to correlate `route-set`s with `aut-num`s.

**Comment by cunha** [comment]
My thoughts were:

1. Compute set of `route` objects that have `origin: ASX`
2. Look at RPSL entries for ASX and whether it has rules like`to AS-ANY export RS-ASX-ROUTES`, *if* (and only if) it does, then compare RS-ASX-ROUTES with the set of routes from (1) above.

**Comment by SichangHe** [comment]
- [ ] How many ASes only export a route set or `ANY`.

**Comment by SichangHe** [comment]
That (145) is double the number I estimated, but still tiny compared to the total number of 50999 ASes with policy.

**Comment by cunha** [comment]
I thought we'd include ASes like AS61574, which only has `announce ANY` in its policy:

```
aut-num:        AS61574
as-name:        PEERING-TESTBED-AS61574
descr:          Columbia/UFMG PEERING Research Testbed
descr:          https://peering.ee.columbia.edu
member-of:      AS-PEERING-TESTBED
mp-import:      afi ipv4.unicast from AS-PEERING-TESTBED accept ANY
mp-export:      afi ipv4.unicast to AS-PEERING-TESTBED announce ANY
mp-import:      afi ipv6.unicast from AS-PEERING-TESTBED accept ANY
mp-export:      afi ipv6.unicast to AS-PEERING-TESTBED announce ANY
tech-c:         IFSC2-RIPE
admin-c:        IFSC2-RIPE
status:         OTHER
mnt-by:         MNT-UUPRT
created:        2017-11-16T13:19:07Z
last-modified:  2020-12-27T18:20:55Z
source:         RIPE-NONAUTH # Filtered
```

**Comment by cunha** [comment]
I checked some of these and they had only one single route-set in their exports. I think we should also allow an AS to have `announce ANY` in addition to `announce RS-WHATEVER`. If you've included these, then I think we can drop this as 145 are too few. To make this more concrete, AS47065 would almost appear on our list (it has `announce ANY` and `announce RS-WHATEVER`), it gets pruned because now we have two distinct route sets.

```
aut-num:        AS47065
as-name:        PEERING-TESTBED-AS47065
descr:          Columbia/UFMG PEERING Research Testbed
descr:          https://peering.ee.columbia.edu
mp-import:      afi ipv4.unicast from AS-ANY accept ANY
mp-export:      afi ipv4.unicast to AS-PEERING-TESTBED announce ANY
mp-export:      afi ipv4.unicast to AS-ANY announce RS-PEERING-TESTBED
mp-import:      afi ipv6.unicast from AS-ANY accept ANY
mp-export:      afi ipv6.unicast to AS-PEERING-TESTBED announce ANY
mp-export:      afi ipv6.unicast to AS-ANY announce RS-PEERING-TESTBED
remarks:        Explicit entries for AMS-IX Routeservers:
mp-import:      afi ipv4.unicast from AS6777 accept ANY
mp-export:      afi ipv4.unicast to AS6777 announce RS-PEERING-TESTBED
mp-import:      afi ipv6.unicast from AS6777 accept ANY
mp-export:      afi ipv6.unicast to AS6777 announce RS-PEERING-TESTBED
remarks:        Explicit entries for Vultr:
mp-import:      afi ipv4.unicast from AS20473 accept ANY
mp-export:      afi ipv4.unicast to AS20473 announce RS-PEERING-TESTBED-DIRECT
mp-import:      afi ipv6.unicast from AS20473 accept ANY
mp-export:      afi ipv6.unicast to AS20473 announce RS-PEERING-TESTBED-DIRECT
tech-c:         IFSC2-RIPE
admin-c:        IFSC2-RIPE
status:         OTHER
mnt-by:         MNT-UUPRT
created:        2017-11-16T13:19:06Z
last-modified:  2022-11-08T15:01:20Z
```

**Comment by SichangHe** [comment]
> I thought we'd include ASes like AS61574, which only has `announce ANY` in its policy:

I did not include these ASes because there is no checking whether their Route Set and ASN point to the same set of prefixes

**Comment by cunha** [comment]
> I did not include these ASes because there is no checking whether their Route Set and ASN point to the same set of prefixes

Right, I deleted the comment after realizing that. Sorry about the overhead.

**Comment by SichangHe** [comment]
> I checked some of these and they had only one single route-set in their exports. I think we should also allow an AS to have `announce ANY` in addition to `announce RS-WHATEVER`. If you've included these, then I think we can drop this as 145 are too few.

Yes, I allow `Any`.
