### ISSUE TITLE
ASes with policies compatible with BGPq3

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#64]
> After reading the man page and running some tests, I think we should consider as "bgpq3-compatible" ASes that use only simple `<filter>` in their RPSL rules, where simple includes:
> 
> * AS12345
> * ANY
> * AS-NAME
> * RS-NAME
> 
> Anything with an except, action, refine, wouldn't work.

—@cunha

- [x] Rerun using latest stats and treat each `REFINE` rule as one rule.

**Comment by SichangHe** [comment]
This is tricker than I thought because we unwrap EXCEPT and REFINE when lexing. My current plan is to just check the filters first and exclude those using "advanced import/export expressions" by simple text search.

**Comment by SichangHe** [comment]
What about, `filter-set`, `address-prefix-set`, `as-set`? Are they also "simple", @cunha?

**Comment by cunha** [comment]
I'd be surprised if `bgpq3` handles `filter-set`s. Can you give me a filter-set by name? We can then just call `bgpq3` on it to see what happens.

If an `address-prefix-set` is a prefix range like `184.164.224.0/19^19-24`, then I think it's fine. `bgpq3` does handle these.

**Comment by SichangHe** [comment]
<details><summary>It does not look like that BGPq3 handles filter sets.</summary>

```sh
$ bgpq3 FLTR-PATHCOM-FOR-CUSTOMERS
ERROR:Unable to parse prefix 'FLTR-PATHCOM-FOR-CUSTOMERS', af=2 (inet), ret=0
ERROR:Unable to parse prefix FLTR-PATHCOM-FOR-CUSTOMERS
ERROR:Unable to add prefix FLTR-PATHCOM-FOR-CUSTOMERS (bad prefix or address-family)
$ bgpq3 AS198412:fltr-BOGON
no ip prefix-list NN
! generated prefix-list NN is empty
ip prefix-list NN deny 0.0.0.0/0
$ bgpq3 fltr-martian6
ERROR:Unable to parse prefix 'fltr-martian6', af=2 (inet), ret=0
ERROR:Unable to parse prefix fltr-martian6
ERROR:Unable to add prefix fltr-martian6 (bad prefix or address-family)
```

</details>

**Comment by SichangHe** [comment]
76303 ASes have their rules compatible with BGPq3 (including ASes without rules).

[as_compatible_with_bgpq3.csv](https://github.com/SichangHe/internet_route_verification/files/12842826/as_compatible_with_bgpq3.csv)

**Comment by cunha** [comment]
OK, apparently it seems most ASes make simple use of the RPSL. But 76K? Weren't the number of ASes with rules about 50K?

**Comment by SichangHe** [comment]
ASes without rules are counted within those 76K because they technically are compatible with BGPq3 based on the rules above.

**Comment by SichangHe** [comment]
- [ ] Filter out the ASes without rules.

**Comment by SichangHe** [comment]
47471 ASes have their rules compatible with BGPq3 (excluding ASes without rules).

[as_compatible_with_bgpq3.csv](https://github.com/SichangHe/internet_route_verification/files/12906261/as_compatible_with_bgpq3.csv)

**Comment by SichangHe** [comment]
Update: 48304 ASes have rules and all compatible with BGPq3, out of 50861 ASes with any rules, out of 78701 `aut-num`s.

**Comment by SichangHe** [comment]
BGPq4 still does not support filter sets. We just need to change `3`s to `4`s.

```sh
$ bgpq4 FLTR-PATHCOM-FOR-CUSTOMERS 
ERROR:Unable to parse prefix 'FLTR-PATHCOM-FOR-CUSTOMERS', af=2 (inet), ret=0
ERROR:Unable to parse prefix FLTR-PATHCOM-FOR-CUSTOMERS
ERROR:Unable to add prefix FLTR-PATHCOM-FOR-CUSTOMERS (bad prefix or address-family)
$ bgpq4 AS198412:fltr-BOGON
no ip prefix-list NN
! generated prefix-list NN is empty
ip prefix-list NN deny 0.0.0.0/0
$ bgpq4 fltr-martian6 
ERROR:Unable to parse prefix 'fltr-martian6', af=2 (inet), ret=0
ERROR:Unable to parse prefix fltr-martian6
ERROR:Unable to add prefix fltr-martian6 (bad prefix or address-family)
```

**Comment by cunha** [comment]
Let's keep BGPq3 in the analysis so we don't need to update the graphs (I
also think it is more well-known), we can mention BGPq4 somewhere suitable
(e.g., related work).

**Comment by cunha** [comment]
Seems we're doing BGPq4 already, sounds good too.

**Comment by SichangHe** [comment]
```python
48190 ASes (94.5%) are compatible with BGPq3 with the ASes that have rules.
```
