### ISSUE TITLE
Updated Neighbors VS Rules Stats considering ASes in ASRelDB but not IRR

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#67]
-1 for neighbor if no data in AS Relationship DB. -1 for import/export if no data in IRR.

<details><summary>Polars output.</summary>

```elixir
shape: (95_911, 4)
┌─────────┬──────────┬────────┬────────┐
│ aut_num ┆ neighbor ┆ import ┆ export │
│ ---     ┆ ---      ┆ ---    ┆ ---    │
│ u64     ┆ i32      ┆ i32    ┆ i32    │
╞═════════╪══════════╪════════╪════════╡
│ 37591   ┆ 2        ┆ -1     ┆ -1     │
│ 204753  ┆ 1        ┆ 3      ┆ 3      │
│ 9689    ┆ 2        ┆ 1      ┆ 1      │
│ 62685   ┆ 4        ┆ -1     ┆ -1     │
│ …       ┆ …        ┆ …      ┆ …      │
│ 262378  ┆ 7        ┆ 1      ┆ 1      │
│ 139330  ┆ 1        ┆ 0      ┆ 0      │
│ 265651  ┆ 1        ┆ -1     ┆ -1     │
│ 17077   ┆ 10       ┆ 8      ┆ 8      │
└─────────┴──────────┴────────┴────────┘
shape: (9, 5)
┌────────────┬───────────────┬────────────┬───────────┬───────────┐
│ describe   ┆ aut_num       ┆ neighbor   ┆ import    ┆ export    │
│ ---        ┆ ---           ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ f64           ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪═══════════════╪════════════╪═══════════╪═══════════╡
│ count      ┆ 95911.0       ┆ 95911.0    ┆ 95911.0   ┆ 95911.0   │
│ null_count ┆ 0.0           ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 125671.693403 ┆ 10.15602   ┆ 4.122249  ┆ 4.008946  │
│ std        ┆ 112437.127515 ┆ 102.243572 ┆ 52.110393 ┆ 48.272178 │
│ min        ┆ 1.0           ┆ -1.0       ┆ -1.0      ┆ -1.0      │
│ 25%        ┆ 34821.0       ┆ 1.0        ┆ 0.0       ┆ 0.0       │
│ 50%        ┆ 62122.0       ┆ 1.0        ┆ 1.0       ┆ 1.0       │
│ 75%        ┆ 205279.5      ┆ 3.0        ┆ 2.0       ┆ 2.0       │
│ max        ┆ 6.131644e6    ┆ 9628.0     ┆ 5724.0    ┆ 5344.0    │
└────────────┴───────────────┴────────────┴───────────┴───────────┘
```

</details>

[as_neighbors_vs_rules.csv](https://github.com/SichangHe/internet_route_verification/files/12908403/as_neighbors_vs_rules.csv)

**Comment by SichangHe** [comment]
![as_neighbor_vs_counts_zoom](https://github.com/SichangHe/internet_route_verification/assets/84777573/a10c3fe4-6b4d-4c80-b6a0-355ec46595e3)

<details>
<summary>Code used.</summary>

```python
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("as_neighbors_vs_rules.csv")
plt.figure(figsize=(15, 15))
plt.scatter(df['neighbor'], df['import'], color='blue', alpha=0.3, s=2, label='Number of Import')
plt.scatter(df['neighbor'], df['export'], color='red', alpha=0.3, s=2, label='Number of Export')
plt.xlabel('Neighbor')
plt.ylabel('Counts')
plt.title('Neighbor Counts vs Import/Export Counts for Autonomous Systems')
plt.legend()
plt.grid(True)
plt.show()
```

</details>

**Comment by SichangHe** [comment]
16960 ASes appear in ASRelDB but not IRR.
20468 ASes appear in IRR but not ASRelDB.
Total: 95911 ASes.

<details>
<summary>IPython.</summary>

```python
In [14]: df[(df['import'] == -1) | (df['export'] == -1)]
Out[14]:
       aut_num  neighbor  import  export
0        37591         2      -1      -1
3        62685         4      -1      -1
6       399566         1      -1      -1
16       11471         1      -1      -1
19       14444         2      -1      -1
...        ...       ...     ...     ...
95883    31957         2      -1      -1
95884    52860         1      -1      -1
95885   264164         2      -1      -1
95895   393635         2      -1      -1
95909   265651         1      -1      -1

[16960 rows x 4 columns]

In [15]: df[(df['neighbor'] == -1)]
Out[15]:
       aut_num  neighbor  import  export
11       55704        -1       0       0
33      202322        -1       3       3
44      199337        -1       2       2
45       44502        -1       1       1
48       24788        -1       0       0
...        ...       ...     ...     ...
95896   142031        -1       0       0
95899    17902        -1       3       3
95900    28529        -1       0       0
95901   208690        -1       0       0
95905   211088        -1       9       9

[20468 rows x 4 columns]
```

</details>

**Comment by cunha** [comment]
> 16960 ASes appear in ASRelDB but not IRR.

Wild. Do you mean ~17K ASes have no import/export rules, or that there are no `aut-num` objects at all?

**Comment by SichangHe** [comment]
> Wild. Do you mean ~17K ASes have no import/export rules, or that there are no `aut-num` objects at all?

No `aut-num` in [IRR databases we use](https://github.com/SichangHe/internet_route_verification/blob/729194b87e6d460d8b3d3676d87691f7e3b179ee/README.md#obtain-irr-data).

**Comment by SichangHe** [comment]
- [ ] whois some of the AS not in IRR.

**Comment by SichangHe** [comment]
I realized a potential problem, @cunha. We are using [the AS Relationship DB from 2013](https://publicdata.caida.org/datasets/2013-asrank-data-supplement/), which is probably outdated.

Maybe we should update to one of [CAIDA's other DBs](https://publicdata.caida.org/datasets/?C=M;O=A) such as [as-relationships](https://publicdata.caida.org/datasets/as-relationships/)?

**Comment by SichangHe** [comment]
No longer latest stats after fixing `default`.

**Comment by SichangHe** [comment]
Covered by #95.

**Comment by cunha** [comment]
> I realized a potential problem, @cunha. We are using [the AS Relationship DB from 2013](https://publicdata.caida.org/datasets/2013-asrank-data-supplement/), which is probably outdated.
> 
> Maybe we should update to one of [CAIDA's other DBs](https://publicdata.caida.org/datasets/?C=M;O=A) such as [as-relationships](https://publicdata.caida.org/datasets/as-relationships/)?

We should definitely be using a newer database. Something to match the IRR datasets we're using. Did you do this at one point?

**Comment by SichangHe** [comment]
No, we are not using databases from 2013. It is just under that folder. It has been undated regularly since and we have been using the July 2023 one.

**Comment by cunha** [comment]
Sounds good. Just checking.
