### ISSUE TITLE
AS ok/skip/unrec/meh/err import/export percentages stacked area plot

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#69]
Previews. Generated with https://github.com/cunha/paper-rpsl-analysis/commit/53cf02c5330c5e945b733741a2643f8b6f75e324

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/40be6c4b-eb23-4687-a975-1790189903ed)

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/1b1b0fb4-ccd1-4f69-b5ba-feede67433f8)

**Comment by SichangHe** [comment]
This result matches [our prediction](https://github.com/SichangHe/internet_route_verification/issues/38#issuecomment-1723814532) very well.
> <img alt="image" width="798" src="https://user-images.githubusercontent.com/325495/268706791-03f03f98-b808-4ea6-a890-0c2c6d1bb359.png">

The parts sorted by %ok are the most chaotic, composing mostly of meh.

The clear straight cut around completely skipped or unrecorded ASes is surprising.

It would be nice to be able to tell which line represents which AS.

**Comment by SichangHe** [comment]
I zoomed in on the plot. The areas next to %ok are mainly meh, but also have a considerable amount of unrecorded, much less errors, and almost no skips.

The areas under %err are mainly meh, with a bit of unrecorded and hardly any skips.

**Comment by cunha** [comment]
This is neat! Something I didn't foresee but makes total sense now that I see it. We have vertical bands because ASes either use the RPSL correctly (OK), don't use it at all (skip/unrecorded), or use it incorrectly (meh/err). It's curious that there are more ASes in the meh/err bands than in the pure-OK bands.

I guess next we should plot only the ases with meh, and then plot the graph breaking down the different Special cases we handle to see if we're going to have bands again. Bands would mean ASes make incorrect but consistent use of the RPSL, while a mix would mean ASes make incorrect and inconsistent use of the RPSL.

**Comment by SichangHe** [comment]
> ASes either use the RPSL correctly (OK), don't use it at all (skip/unrecorded), or use it incorrectly (meh/err).

This is actually not true. Some ASes have both ok and err, some have ok and unrec.

> It's telling that there are more ASes in the meh/err bands than in the pure-OK bands.

This is only true for imports.

> I guess next we should plot only the ases with meh

I think we will also need to consider the ASes with ok + unrec, etc.

> and then plot the graph breaking down the different Special cases we handle to see if we're going to have bands again.

We probably will. Then, that's another rabbit hole.

**Comment by cunha** [comment]
> This is actually not true. Some ASes have both ok and err, some have ok and unrec.

Right, I was focusing on the vertical bands. I should have listed one for the ASes with mixed behavior.

> This is only true for imports.

I meant that the OK+meh, meh, and meh+err bands are wider than the pure-OK band on the left. This seems to hold for both import and export.

**Comment by SichangHe** [comment]
[AS-export-percentages-stacked-area-squared.pdf](https://github.com/SichangHe/internet_route_verification/files/13188962/AS-export-percentages-stacked-area-squared.pdf)
[AS-export-percentages-stacked-area.pdf](https://github.com/SichangHe/internet_route_verification/files/13188964/AS-export-percentages-stacked-area.pdf)
[AS-import-percentages-stacked-area-squared.pdf](https://github.com/SichangHe/internet_route_verification/files/13188966/AS-import-percentages-stacked-area-squared.pdf)
[AS-import-percentages-stacked-area.pdf](https://github.com/SichangHe/internet_route_verification/files/13188967/AS-import-percentages-stacked-area.pdf)

**Comment by SichangHe** [comment]
Different sorting order.

<details><summary>If sorted from "err" to "ok".</summary>

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/14f71bac-cae9-4d8c-a11e-34a3a12943c8)
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/7e0d3eb4-9d67-4dd5-8ecf-1db66765b92c)

The "ok" band becomes clear-cut.

</details>
<details><summary>If sorted from "ok" to "err".</summary>

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/b55d7a60-ad0c-4b34-a944-e3ab4eff0d77)
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/c4aaad04-f8b2-4050-89ce-66333a52b166)

Almost the same as the original, except for the sight slope between "unrec" and "meh".

</details>

**Comment by cunha** [comment]
These are useful, we can choose which version fits the text best when
writing the evaluation section.
