### ISSUE TITLE
AS with `route`s/`route6` but no `aut-num`

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#76]
In #57, we have 78951 aut-nums, but also 87534 "AS Routes", `route`/`route6` objects grouped by the ASes they originate from. This means that at least 8583 `route`/`route6` objects refer to ASes not recorded in the IRR.

- [ ] Report the number.
- [ ] Find these ASes that have routes but no AutNum objects.

**Comment by SichangHe** [comment]
Someone creating `route` but not `aut-num` or creating `route` for someone else.

**Comment by SichangHe** [comment]
<details><summary>19468 ASes with `route`s/`route6`s without `aut-num`.</summary>

[as_w_routes_wo_aut_num.csv](https://github.com/SichangHe/internet_route_verification/files/14078955/as_w_routes_wo_aut_num.csv)
```python
In [3]: df
Out[3]:
       as_num  n_route
0       16878        5
1       53176        6
2       23640        8
3       62845        1
4      267648        6
...       ...      ...
19463  269184        8
19464   14890        2
19465   40425        2
19466   28113        1
19467   10876        2

[19468 rows x 2 columns]

In [4]: df.describe()
Out[4]:
             as_num       n_route
count  1.946800e+04  19468.000000
mean   3.197686e+07     11.634991
std    3.674438e+08    138.043438
min    2.000000e+00      1.000000
25%    2.281175e+04      1.000000
50%    5.273450e+04      2.000000
75%    2.684238e+05      6.000000
max    4.294967e+09  14938.000000
```

Commit: afac595

</details>

**Comment by SichangHe** [comment]
<details><summary>4911 AS Sets contain unrecorded `aut-num`s.</summary>

```rust
>>     query
        .as_sets
        .par_values()
        .filter(|as_set| !as_set.unrecorded_members.is_empty())
        .count()

4911
```

</details>

**Comment by SichangHe** [comment]
> I'd like to have a look at some of the ASes that appear in route objects but do not have aut-nums. Are we somehow missing a registry? Maybe national registries like NIC.br?

@cunha, do you want to look at the ASes?

**Comment by cunha** [comment]
Yeah, I'd want to know that the ASNs are.

**Comment by SichangHe** [comment]
> 19468 ASes with `route`s/`route6`s without `aut-num`.
> [as_w_routes_wo_aut_num.csv](https://github.com/SichangHe/internet_route_verification/files/14078955/as_w_routes_wo_aut_num.csv)
> 
> ```python
> In [3]: df
> Out[3]:
>        as_num  n_route
> 0       16878        5
> 1       53176        6
> 2       23640        8
> 3       62845        1
> 4      267648        6
> ...       ...      ...
> 19463  269184        8
> 19464   14890        2
> 19465   40425        2
> 19466   28113        1
> 19467   10876        2
> 
> [19468 rows x 2 columns]
> 
> In [4]: df.describe()
> Out[4]:
>              as_num       n_route
> count  1.946800e+04  19468.000000
> mean   3.197686e+07     11.634991
> std    3.674438e+08    138.043438
> min    2.000000e+00      1.000000
> 25%    2.281175e+04      1.000000
> 50%    5.273450e+04      2.000000
> 75%    2.684238e+05      6.000000
> max    4.294967e+09  14938.000000
> ```
> 
> Commit: [afac595](https://github.com/SichangHe/internet_route_verification/commit/afac595817a62560493c785024b46a616452efb8)

Here are the ASNs.

**Comment by cunha** [comment]
So, it seems most of these ASes exist. Here is what some manual evalutation turns out:

```
16878,5  #ARIN **
53176,6  #NIC.br  no match
23640,8  #JPNIC **
62845,1  #ARIN **
267648,6  #REGISTRO.br
400672,3  #ARIN **
54112,8  #ARIN **
271217,4  #REGISTRO.br visible
266141,38  #REGISTRO.br
```

* The ARIN ASes are allocated and assigned, but do not use ARIN's Routing Registry, so they have zero RPSL rules.
* The NIC.br and JPNIC ASes exist, but we don't have databases for them.

Possible avenues to pursue:

- [ ] Obtain the missing databases (may be unavailable)
- [ ] Identify which range of ASNs belong to which regional registrar, so we know which ASes are managed by NIC.br, JPNIC, KRNIC and others. What we want is something like [this allocation table](https://www.iana.org/assignments/as-numbers/as-numbers.xhtml), but from the continental registrars to the regional registrars.
