### ISSUE TITLE
`default`/`mp-default`: count as import or export?

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#87]

**Comment by SichangHe** [comment]
In our conversation just now, we reasoned that it should be "import" because the packets go _to_ the peer and the route should propagate in the other direction. But, in a19286b2 in June we decided to count them as "export" for some reason.

**Comment by SichangHe** [comment]
Counting `default` as `import` in 6ff97d6d01445d6f848d0facf7eda25f38bdcf9c.

**Comment by SichangHe** [comment]
> While writing the message to Job I convinced myself that it really doens't make sense to `OK` this route based on the `default`. The `default` might actually never manifest on AS-paths, so we might as well ignore it on when checking the paths observed on BGP. The `default` should only impact data-plane traffic, which we don't have visibility of.

—https://github.com/SichangHe/internet_route_verification/issues/83#issuecomment-1801897443

However, I think the following sentence from the RFC indicates that `default` affects routes propagation and is related to `import`:

> A router only uses the default policy if it **received**
   the **routes** matched by <filter> from this peer.

**Comment by cunha** [comment]
Right, but this is under the filter documentation, right? I understood it
to mean that the default only kicks in (and steer data plane traffic) if
the filter matches. Even if the filter matches, there is no visible BGP
announcement or route propagation.

**Comment by SichangHe** [comment]
Do we also say "receive routes" on the data plane?

**Comment by cunha** [comment]
On the data plane we usually talk about receiving and sending packets
(or flows). Routes are primarily a control-plane concept.
