### ISSUE TITLE
AS unrecorded case percentages stacked area plot

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#92]
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/87c0827a-ccd3-43fc-8ffb-bc9c6374c303)

[AS-unrec-case-percentages-stacked-area-squared.pdf](https://github.com/SichangHe/internet_route_verification/files/13315622/AS-unrec-case-percentages-stacked-area-squared.pdf)
[AS-unrec-case-percentages-stacked-area.pdf](https://github.com/SichangHe/internet_route_verification/files/13315626/AS-unrec-case-percentages-stacked-area.pdf)

Generated using https://github.com/SichangHe/internet_route_verification_meta/commit/79eeb32325a9002f877ffc511f23645be15b12bf and data in #89.

**Comment by SichangHe** [comment]
Surprisingly, although `unrec_import_empty` and `unrec_export_empty` has similar averages, much more AS have the latter. This is also shown in the 75 percentile. All these ASes have no other unrecorded cases.

The large stripe of `unrec_aut_num` shows that many ASes are not recorded in the IRR.

Most of the rest are unrecorded routes and AS Sets.

**Comment by cunha** [comment]
Are the unrecorded aut-num objects concentrated in one or two RIR/NIRs?

**Comment by SichangHe** [comment]
Here's a list of ASes with `unrec_aut_num`: [as_w_unrec_aut_num.csv](https://github.com/SichangHe/internet_route_verification/files/13319148/as_w_unrec_aut_num.csv)
I don't have a good way to know which registry they are in because we don't record that information.

For the list of missing ASes (which is what you are probably asking for), I need to write a script to generate all the reports again and extract them out from the report items.

**Comment by SichangHe** [comment]
None of the above 17108 ASes have associated AutNum objects in the IRR (just realized that is the reason why they are reported as unrecorded in the first place after trying to extract `source` for the registry they are in).

I could find some of them as `origin` in `route`/`route6` objects, though. However, according to #76, there are only 8583 more ASes specified as `origin` than there are AutNum objects. This might be caused by a subset of ASes that have route objects but no AutNum objects.

**Comment by SichangHe** [comment]
I rg'ed 10 of them, they have routes in RADB, ARIN, JPIRR, ALTDB, LEVEL3, and get referred to as members in additionally RIPE, NTTCOM. So, they are not concentrated in a few registries.

**Comment by cunha** [comment]
I had a look at some of the ASes, they seem to be registered in the ARIN region (`whois ASNUM`) gets a response from `whois.arin.net`, but when we query the routing registry (`whois -h rr.arin.net ASNUM`) we do not get anything. It seems OK to consider these ASes as not having any rule.

@cunha e-mail Randy about what could this be.

**Comment by cunha** [comment]
The 5 I checked had entries on whois.arin.net, but not rr.arin.net, which I
think we should consider similarly to ASes not declaring any import/export
rue.

**Comment by SichangHe** [comment]
Factoring in the special case ratio (blank part for non-special cases):

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/098a6251-a31a-4f3d-b4ee-e958709dd2c9)

Commit: https://github.com/SichangHe/internet_route_verification_meta/commit/f7bc65d2fee244eb55d27daaee8305d126c60854

**Comment by SichangHe** [comment]
Interestingly, some ASes have `unrec_import_empty` mixed with non-unrecorded cases, but not the other way round (export).

Those non-unrecorded cases have to be exports.

**Comment by SichangHe** [comment]
<details><summary>Latest plots.</summary>

![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/ec424561-fd26-4cd3-9a73-35ae31e260e4)
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/53944792-81d3-47e5-85c5-65d043adc8c3)

[AS-unrec-case-percentages-stacked-area-squared.pdf](https://github.com/SichangHe/internet_route_verification/files/13701211/AS-unrec-case-percentages-stacked-area-squared.pdf)
[AS-unrec-case-percentages-stacked-area.pdf](https://github.com/SichangHe/internet_route_verification/files/13701212/AS-unrec-case-percentages-stacked-area.pdf)

</details>

**Comment by SichangHe** [comment]
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/7f34c65f-6837-49e5-ab7a-cb847fbb3920)

All RIBs.
