### ISSUE TITLE
Route unrecorded case percentages stacked area plot

### ISSUE THREAD

**Issue by SichangHe** [SichangHe/internet_route_verification#93]
![image](https://github.com/SichangHe/internet_route_verification/assets/84777573/e12dbdc9-fc73-47e8-9307-9090b77876f3)

[route-unrec-case-percentages-stacked-area-squared.pdf](https://github.com/SichangHe/internet_route_verification/files/13315994/route-unrec-case-percentages-stacked-area-squared.pdf)
[route-unrec-case-percentages-stacked-area.pdf](https://github.com/SichangHe/internet_route_verification/files/13315995/route-unrec-case-percentages-stacked-area.pdf)

Generated using  and data in #88.

**Comment by cunha** [comment]
If a route has no unrecorded case, then it doesn't show up in this graph?
If a route has one unrecorded case and many OKs, then it shows up here as a
100% single-color vertical line?

**Comment by SichangHe** [comment]
> If a route has no unrecorded case, then it doesn't show up in this graph?

Correct.
> If a route has one unrecorded case and many OKs, then it shows up here as a
100% single-color vertical line?

Correct.

**Comment by SichangHe** [comment]
<details><summary>There are only 111 ASes with only 1 unrec, though.</summary>

```python
In [9]: d = pd.DataFrame({"total": sum(df[tag] for tag in TAGS)})

In [10]: d
Out[10]:
       total
0        280
1         60
2        964
3          0
4        258
...      ...
75372    236
75373      0
75374    508
75375     30
75376     60

[75377 rows x 1 columns]

In [11]: d.describe()
Out[11]:
              total
count  7.537700e+04
mean   4.659257e+05
std    8.056041e+07
min    0.000000e+00
25%    0.000000e+00
50%    2.800000e+01
75%    8.700000e+01
max    2.152287e+10

In [13]: d[d['total'] > 0].describe()
Out[13]:
              total
count  3.925400e+04
mean   8.946881e+05
std    1.116336e+08
min    1.000000e+00
25%    3.000000e+01
50%    8.400000e+01
75%    2.020000e+02
max    2.152287e+10

In [14]: d[d['total'] == 0].count()
Out[14]:
total    36123
dtype: int64

In [15]: d[d['total'] == 1].count()
Out[15]:
total    111
```

</details>
